[build]
  command = "npm run build"
  publish = ".next"

[functions]
  node_bundler = "esbuild"
  # Support for institutional on-chain attestation latency
  timeout = 26 

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NODE_VERSION = "20"
  NEXT_USE_NETLIFY_EDGE = "true"

[context.deploy-preview.environment]
  NODE_VERSION = "20"
